#!/usr/bin/env ruby
require 'rubygems'
require File.dirname(__FILE__) + '/../lib/connect'

Connector.connect
  
ActiveRecord::Schema.define do 
      create_table :links do |t|
        t.column :text, :string
        t.column :url, :string
        t.column :page, :string
        t.column :scraped, :boolean 
      end   
end
  

