#!/usr/bin/env ruby
require 'rubygems'
require File.dirname(__FILE__) + '/../lib/connect'

Connector.connect
  
ActiveRecord::Schema.define do 
      create_table :links do |t|
        t.column :text, :string
        t.column :url, :string
        t.column :page_id, :integer
      end
      
      create_table :titles do |t|
        t.column :text, :string
        t.column :page_id, :integer
      end
      
      create_table :pages do |t|
        t.column :url, :string
        t.column :scraped, :boolean 
      end
      
      create_table :headings do |t|
        t.column :text, :string
        t.column :size, :integer
        t.column :page_id, :integer
      end 
      
      add_index :pages, [:url]  
end
  

